//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duck.Cameras.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duck.Cameras.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        internal static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3B3B3B.
        /// </summary>
        internal static string card_bg_color {
            get {
                return ResourceManager.GetString("card_bg_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #5B5B5B.
        /// </summary>
        internal static string card_image_bg_color {
            get {
                return ResourceManager.GetString("card_image_bg_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3B3B3B.
        /// </summary>
        internal static string card_title_bg_color {
            get {
                return ResourceManager.GetString("card_title_bg_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EEEEEE.
        /// </summary>
        internal static string card_title_text_color {
            get {
                return ResourceManager.GetString("card_title_text_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI.
        /// </summary>
        internal static string default_font {
            get {
                return ResourceManager.GetString("default_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon_back {
            get {
                object obj = ResourceManager.GetObject("icon_back", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon_close {
            get {
                object obj = ResourceManager.GetObject("icon_close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_logo {
            get {
                object obj = ResourceManager.GetObject("icon_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon_maximize {
            get {
                object obj = ResourceManager.GetObject("icon_maximize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon_minimize {
            get {
                object obj = ResourceManager.GetObject("icon_minimize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon_reload {
            get {
                object obj = ResourceManager.GetObject("icon_reload", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon_restore {
            get {
                object obj = ResourceManager.GetObject("icon_restore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon_settings {
            get {
                object obj = ResourceManager.GetObject("icon_settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #262626.
        /// </summary>
        internal static string page_bg_color {
            get {
                return ResourceManager.GetString("page_bg_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BC0090.
        /// </summary>
        internal static string primary_200 {
            get {
                return ResourceManager.GetString("primary_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BC2C00.
        /// </summary>
        internal static string primary_500 {
            get {
                return ResourceManager.GetString("primary_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BC0032.
        /// </summary>
        internal static string primary_700 {
            get {
                return ResourceManager.GetString("primary_700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00EFAF.
        /// </summary>
        internal static string secondary_200 {
            get {
                return ResourceManager.GetString("secondary_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00BC8A.
        /// </summary>
        internal static string secondary_700 {
            get {
                return ResourceManager.GetString("secondary_700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #50808080.
        /// </summary>
        internal static string spinner_bg_color {
            get {
                return ResourceManager.GetString("spinner_bg_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        internal static string spinner_node_border_color {
            get {
                return ResourceManager.GetString("spinner_node_border_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        internal static string spinner_node_fill_color {
            get {
                return ResourceManager.GetString("spinner_node_fill_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        internal static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///    &lt;s:Body&gt;
        ///        &lt;ContinuousMove xmlns=&quot;http://www.onvif.org/ver20/ptz/wsdl&quot;&gt;
        ///            &lt;ProfileToken&gt;{0:s}&lt;/ProfileToken&gt;
        ///            &lt;Velocity&gt;
        ///                &lt;PanTilt x=&quot;{1:f}&quot; y=&quot;{2:f}&quot; xmlns=&quot;http://www.onvif.org/ver10/schema&quot; /&gt;
        ///            &lt;/Velocity&gt;
        ///        &lt;/ContinuousMove&gt;
        ///    &lt;/s:Body&gt;
        ///&lt;/s:Envelope&gt;.
        /// </summary>
        internal static string ws_continuous_move {
            get {
                return ResourceManager.GetString("ws_continuous_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:tds=&quot;http://www.onvif.org/ver10/device/wsdl&quot;
        ///    xmlns:tns=&quot;http://schemas.xmlsoap.org/ws/2005/04/discovery&quot;
        ///    xmlns:wsa=&quot;http://schemas.xmlsoap.org/ws/2004/08/addressing&quot;&gt;
        ///    &lt;soap:Header&gt;
        ///        &lt;wsa:MessageID&gt;urn:uuid:{0:s}&lt;/wsa:MessageID&gt;
        ///        &lt;wsa:To&gt;urn:schemas-xmlsoap-org:ws:2005:04:discovery&lt;/wsa:To&gt;
        ///        &lt;wsa:Action&gt;http://schemas.xmlsoap.org/ws/2005/04/discovery/Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ws_discovery_probe {
            get {
                return ResourceManager.GetString("ws_discovery_probe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:d=&quot;http://schemas.xmlsoap.org/ws/2005/04/discovery&quot;
        ///    xmlns:dn=&quot;http://www.onvif.org/ver10/network/wsdl&quot;
        ///    xmlns:wsa=&quot;http://schemas.xmlsoap.org/ws/2004/08/addressing&quot;&gt;
        ///    &lt;SOAP-ENV:Header&gt;
        ///        &lt;wsa:MessageID&gt;urn:uuid:27416298-5566-7788-99ac-30fff68b6b51&lt;/wsa:MessageID&gt;
        ///        &lt;wsa:RelatesTo&gt;urn:uuid:e064ac39-7665-4cba-bba5-2141f89f3d91&lt;/wsa:RelatesTo&gt;
        ///        &lt;wsa:T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ws_emulator_response {
            get {
                return ResourceManager.GetString("ws_emulator_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:tptz=&quot;http://www.onvif.org/ver20/ptz/wsdl&quot;&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;tptz:GetConfigurations /&gt;
        ///    &lt;/soap:Body&gt;
        ///&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string ws_get_configurations {
            get {
                return ResourceManager.GetString("ws_get_configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:tptz=&quot;http://www.onvif.org/ver20/ptz/wsdl&quot;&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;tptz:GetConfigurationOptions&gt;
        ///            &lt;tptz:ConfigurationToken&gt;{0:s}&lt;/tptz:ConfigurationToken&gt;
        ///        &lt;/tptz:GetConfigurationOptions&gt;
        ///    &lt;/soap:Body&gt;
        ///&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string ws_get_configurations_options {
            get {
                return ResourceManager.GetString("ws_get_configurations_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:tds=&quot;http://www.onvif.org/ver10/device/wsdl&quot;&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;tds:GetDeviceInformation /&gt;
        ///    &lt;/soap:Body&gt;
        ///&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string ws_get_device_information {
            get {
                return ResourceManager.GetString("ws_get_device_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:trt=&quot;http://www.onvif.org/ver10/media/wsdl&quot;&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;trt:GetProfiles /&gt;
        ///    &lt;/soap:Body&gt;
        ///&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string ws_get_profiles {
            get {
                return ResourceManager.GetString("ws_get_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:tds=&quot;http://www.onvif.org/ver10/device/wsdl&quot;&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;tds:GetServices&gt;
        ///            &lt;tds:IncludeCapability&gt;false&lt;/tds:IncludeCapability&gt;
        ///        &lt;/tds:GetServices&gt;
        ///    &lt;/soap:Body&gt;
        ///&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string ws_get_services {
            get {
                return ResourceManager.GetString("ws_get_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:trt=&quot;http://www.onvif.org/ver10/media/wsdl&quot;&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;trt:GetSnapshotUri&gt;
        ///            &lt;trt:ProfileToken&gt;{0:s}&lt;/trt:ProfileToken&gt;
        ///        &lt;/trt:GetSnapshotUri&gt;
        ///    &lt;/soap:Body&gt;
        ///&lt;/soap:Envelope&gt;
        ///.
        /// </summary>
        internal static string ws_get_snapshot_uri {
            get {
                return ResourceManager.GetString("ws_get_snapshot_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:tptz=&quot;http://www.onvif.org/ver20/ptz/wsdl&quot;
        ///    xmlns:trt=&quot;http://www.onvif.org/ver10/media/wsdl&quot;&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;tptz:GetStatus&gt;
        ///            &lt;trt:ProfileToken&gt;{0:s}&lt;/trt:ProfileToken&gt;
        ///        &lt;/tptz:GetStatus&gt;
        ///    &lt;/soap:Body&gt;
        ///&lt;/soap:Envelope&gt;.
        /// </summary>
        internal static string ws_get_status {
            get {
                return ResourceManager.GetString("ws_get_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot;
        ///    xmlns:trt=&quot;http://www.onvif.org/ver10/media/wsdl&quot;
        ///    xmlns:tt=&quot;http://www.onvif.org/ver10/schema&quot;&gt;
        ///    &lt;soap:Body&gt;
        ///        &lt;trt:GetStreamUri&gt;
        ///            &lt;trt:StreamSetup&gt;
        ///                &lt;trt:Stream&gt;RTP-Unicast&lt;/trt:Stream&gt;
        ///                &lt;tt:Transport&gt;
        ///                    &lt;tt:Protocol&gt;RTSP&lt;/tt:Protocol&gt;
        ///                &lt;/tt:Transport&gt;
        ///            &lt;/trt:StreamSetup&gt;
        ///            &lt;trt: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ws_get_stream_uri {
            get {
                return ResourceManager.GetString("ws_get_stream_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///    &lt;s:Body&gt;
        ///        &lt;GotoPreset xmlns=&quot;http://www.onvif.org/ver20/ptz/wsdl&quot;&gt;
        ///            &lt;ProfileToken&gt;{0:s}&lt;/ProfileToken&gt;
        ///            &lt;PresetToken&gt;{1:s}&lt;/PresetToken&gt;
        ///        &lt;/GotoPreset&gt;
        ///    &lt;/s:Body&gt;
        ///&lt;/s:Envelope&gt;.
        /// </summary>
        internal static string ws_goto_preset {
            get {
                return ResourceManager.GetString("ws_goto_preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot;&gt;
        ///    &lt;s:Body&gt;
        ///        &lt;Stop xmlns=&quot;http://www.onvif.org/ver20/ptz/wsdl&quot;&gt;
        ///            &lt;ProfileToken&gt;{0:s}&lt;/ProfileToken&gt;
        ///            &lt;PanTilt&gt;true&lt;/PanTilt&gt;
        ///            &lt;Zoom&gt;true&lt;/Zoom&gt;
        ///        &lt;/Stop&gt;
        ///    &lt;/s:Body&gt;
        ///&lt;/s:Envelope&gt;.
        /// </summary>
        internal static string ws_stop {
            get {
                return ResourceManager.GetString("ws_stop", resourceCulture);
            }
        }
    }
}
